app/views/aritomo/customer_info_edit.html.erb
app/views/aritomo/customor_confirm.html.erb
app/views/aritomo/mypage.html.erb
app/views/aritomo/order_info.html.erb
app/views/aritomo/shipping_address_edit.html.erb
app/views/aritomo/shipping_addresses_new_index.html.erb
app/views/aritomo/thankyoufor_order.html.erb
app/views/aritomo/withdrawal_confirm.html.erb

aritomoが作成したワイヤーフレームのviewを追加しました

aritomo view

---

app/views/morota/product.edit.html.erb

morota view

---

config/routes.rb
db/migrate/20200617092844_devise_create_customers.rb
db/migrate/20200618012457_create_cart_items.rb
db/migrate/20200618013124_create_orders.rb
db/migrate/20200618013757_create_addresses.rb
db/migrate/20200618014301_create_order_items.rb
db/migrate/20200618014840_create_products.rb
db/migrate/20200618015511_create_genres.rb
db/schema.rb

Add null:false

---

.gitignore
app/models/address.rb
app/models/cart_item.rb
app/models/customer.rb
app/models/genre.rb
app/models/order.rb
app/models/order_item.rb
app/models/product.rb

Add association And enum

---

app/views/tomoya/homes.html.erb
app/views/tomoya/order_histories.index.html.erb
app/views/tomoya/order_histories.show.html.erb
app/views/tomoya/product.show.html.erb
app/views/tomoya/product_new.html.erb
app/views/tomoya/products.index.html.erb
app/views/tomoya/session_sign_in.html.erb

tomoya view

---

.gitignore
app/controllers/admins/products_controller.rb
app/views/tomoya/product_new.html.erb

add gitignore

---

app/views/admins/homes/top.html.erb

morota test

---

app/controllers/admins/genres_controller.rb
app/controllers/admins/products_controller.rb
app/models/product.rb
app/views/admins/genres/index.html.erb
app/views/admins/products/index.html.erb
app/views/admins/products/new.html.erb
app/views/admins/products/show.html.erb
config/puma.rb

Add product and genre

---

app/controllers/admins/genres_controller.rb
app/controllers/admins/products_controller.rb
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb
app/views/admins/products/edit.html.erb
app/views/admins/products/index.html.erb
app/views/admins/products/new.html.erb
app/views/admins/products/show.html.erb

Add admins products genres

---

app/controllers/admins/customers_controller.rb
app/controllers/customers/customers_controller.rb
app/views/morota/admins.customers.edit.html.erb
app/views/morota/admins.customers.index.html.erb
app/views/morota/admins.customers.show.html.erb

admin_customerのビューとコントローラーを追加しました。

[Add]admin_customer.view

---

app/views/layouts/admins.html.erb

Fix ヘッダーのリンク

---

app/controllers/admins/sessions_controller.rb
app/controllers/application_controller.rb
app/controllers/customers/sessions_controller.rb
app/views/layouts/admins.html.erb

Fix sign_upとsign_outの設定修正

---

app/controllers/customers/addresses_controller.rb
app/views/customers/addresses/edit.html.erb
app/views/customers/addresses/index.html.erb
app/views/layouts/admins.html.erb
app/views/layouts/customers.html.erb

Add address controller & view完成

Add address controller & view完成

---

app/assets/stylesheets/application.scss
app/controllers/admins/genres_controller.rb
app/controllers/admins/products_controller.rb
app/controllers/customers/products_controller.rb
app/views/admins/products/edit.html.erb
app/views/admins/products/index.html.erb
app/views/admins/products/show.html.erb
app/views/customers/products/index.html.erb
app/views/customers/products/show.html.erb

プロダクトとジャンルのおおよその機能を追加しました。
ジャンル検索、売り切れ表示、税込み価格、CSSはまだです。

add product and genre not finish

---

app/controllers/customers/customers_controller.rb
app/views/aritomo/delete.html.erb
app/views/customers/customers/delete.html.erb
app/views/customers/customers/edit.html.erb
app/views/customers/customers/show.html.erb

[Fix]Mypage

---

app/assets/javascripts/customers/order_items.coffee
app/assets/stylesheets/customers/order_items.scss
app/controllers/customers/order_items_controller.rb
app/helpers/customers/order_items_helper.rb
app/views/customers/customers/show.html.erb
config/routes.rb
test/controllers/customers/order_items_controller_test.rb

[Add order_items controller & view & routes]

[Add order_items controller & view & routes]

---

app/controllers/admins/genres_controller.rb
app/controllers/customers/cart_items_controller.rb
app/controllers/customers/products_controller.rb
app/views/admins/genres/index.html.erb
app/views/admins/products/index.html.erb
app/views/customers/cart_items/show.html.erb
app/views/customers/products/genre_search.html.erb

Add cart view

---

app/controllers/customers/cart_items_controller.rb
app/controllers/customers/products_controller.rb
app/views/customers/cart_items/show.html.erb
app/views/customers/homes/top.html.erb
app/views/customers/products/show.html.erb
app/views/layouts/admins.html.erb

Add cart not finish and fix route

Add cart not finish and fix route

---

app/controllers/customers/customers_controller.rb
app/controllers/customers/sessions_controller.rb
app/models/customer.rb
app/views/customers/customers/delete.html.erb
config/routes.rb

Add 退会後、ログインできない機能作成

---

app/controllers/customers/cart_items_controller.rb
app/controllers/customers/orders_controller.rb
app/controllers/customers/products_controller.rb
app/views/customers/cart_items/show.html.erb
app/views/customers/orders/new.html.erb
app/views/customers/products/show.html.erb
app/views/layouts/customers.html.erb

cart finish and header fix

---

app/controllers/admins/customers_controller.rb
app/views/admins/customers/edit.html.erb
app/views/admins/customers/index.html.erb
app/views/admins/customers/show.html.erb

Add admins::customers controller & view

Add admins::customers controller & view

---

app/assets/stylesheets/application.scss
app/controllers/customers/products_controller.rb
app/views/customers/homes/top.html.erb
app/views/customers/products/genre_search.html.erb
app/views/customers/products/index.html.erb
app/views/customers/products/show.html.erb
app/views/layouts/admins.html.erb
app/views/layouts/customers.html.erb

[Change header font etc]

---

app/assets/stylesheets/application.scss
app/views/admins/products/new.html.erb
app/views/customers/homes/top.html.erb
app/views/customers/products/index.html.erb
app/views/layouts/admins.html.erb
app/views/layouts/customers.html.erb

[Add scss & change view]

---

app/controllers/customers/order_items_controller.rb
app/controllers/customers/orders_controller.rb
app/views/customers/order_items/index.html.erb
app/views/customers/order_items/show.html.erb
app/views/layouts/customers.html.erb

Add order history and Fix header link

Add order history and Fix header link

---

app/controllers/customers/products_controller.rb
app/views/customers/addresses/edit.html.erb
app/views/customers/addresses/index.html.erb
app/views/customers/order_items/index.html.erb
app/views/customers/products/index.html.erb

[Add pagination & change etc]

---

app/controllers/admins/homes_controller.rb
app/views/admins/customers/edit.html.erb
app/views/admins/customers/index.html.erb
app/views/admins/customers/show.html.erb
app/views/admins/genres/edit.html.erb
app/views/admins/genres/index.html.erb
app/views/admins/homes/top.html.erb
app/views/customers/addresses/edit.html.erb
app/views/customers/addresses/index.html.erb
app/views/customers/order_items/index.html.erb
app/views/customers/order_items/show.html.erb
app/views/layouts/admins.html.erb

[Add admins/homes/top]

---

app/controllers/customers/orders_controller.rb
app/models/address.rb
app/views/customers/orders/new.html.erb

Add orderで登録済の住所選択機能

---

app/controllers/admins/genres_controller.rb
app/controllers/admins/order_items_controller.rb
app/controllers/admins/orders_controller.rb
app/controllers/admins/products_controller.rb

Add admin側の直打ち対策

---

app/controllers/customers/orders_controller.rb
app/views/customers/orders/new.html.erb

[Add Orders controller & view]

[Add Orders controller & view]

---

app/views/admins/order_items/index.html.erb
app/views/admins/order_items/show.html.erb
app/views/admins/orders/index.html.erb
app/views/admins/orders/show.html.erb
app/views/admins/products/edit.html.erb
app/views/admins/products/show.html.erb
app/views/customers/orders/confirm.html.erb
app/views/customers/orders/new.html.erb

[Change layouts etc]

---

app/controllers/admins/orders_controller.rb
app/controllers/customers/order_items_controller.rb
app/views/customers/homes/top.html.erb
app/views/customers/products/genre_search.html.erb
app/views/customers/products/index.html.erb
config/application.rb

[Change etc]

---

app/controllers/customers/orders_controller.rb
app/views/customers/customers/delete.html.erb
app/views/customers/registrations/new.html.erb

Update Orderのバリデーション 設定　＆　退会機能の誤文字編集　＆　sign_upのレイアウト編集

Update Orderのバリデーション 設定　＆　退会機能の誤文字編集　＆　sign_upのレイアウト編集

---

app/views/admins/products/edit.html.erb

[Fix admins/products/edit]

---

app/models/product.rb
app/views/customers/homes/top.html.erb
app/views/customers/products/genre_search.html.erb
app/views/customers/products/index.html.erb
app/views/customers/products/show.html.erb

プロダクトの売り切れ関係＆ジャンルの売り切れ関係修正
商品投稿に写真のバリデーション

fix c.product & homes top & Add product pic

---

app/views/admins/customers/show.html.erb
app/views/layouts/admins.html.erb
app/views/layouts/application.html.erb
app/views/layouts/customers.html.erb

Fix admins/customeのレイアウト　＆　ヘッダー変更　＆　head title変更

Fix admins/customeのレイアウト　＆　ヘッダー変更　＆　head title変更

---

app/views/customers/homes/top.html.erb

[Tax-included price_2]

---

app/controllers/admins/order_items_controller.rb
app/controllers/admins/orders_controller.rb
app/controllers/admins/products_controller.rb
app/views/admins/orders/show.html.erb

注文ステータスと制作ステータスを連動させて、アドミンのプロダクトのリダイレクトを直しました

fix order status and admins product routes

---

app/models/address.rb

[Add]varidation

---

app/views/customers/homes/top.html.erb
app/views/customers/products/genre_search.html.erb
app/views/customers/products/index.html.erb
app/views/customers/products/show.html.erb

商品を税込み価格にして、ジャンルで無効なものは表示しないようにしました

product price tax and genre.is_active

---

app/views/customers/homes/top.html.erb
app/views/customers/products/genre_search.html.erb
app/views/customers/products/index.html.erb
app/views/customers/products/show.html.erb

[Add Tax-included price]

---

app/assets/stylesheets/application.scss
app/views/admins/products/edit.html.erb
app/views/layouts/admins.html.erb

Add searchタグ＆レイアウト　％ Fix　admin/product/edit formの位置を変更

Add searchタグ＆レイアウト　％ Fix　admin/product/edit formの位置を変更

---

app/controllers/admins/homes_controller.rb
app/views/admins/homes/top.html.erb

Add adminのtopから注文情報を可視化

---

app/controllers/admins/order_items_controller.rb
app/views/admins/orders/show.html.erb

order_itemの注文ステータスのform_forで更新ができない箇所を修正

fix order_item form_for
